import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";

import { Footer, Header } from "@/components/layout";
import { Providers } from "@/app/providers";
import { DEFAULT_LOCALE, type Locale } from "@/lib/i18n";
import { LOCALE_COOKIE_KEY } from "@/components/i18n/I18nProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get(LOCALE_COOKIE_KEY)?.value;
  const initialLocale: Locale =
    cookieLocale === "en" || cookieLocale === "hi" ? cookieLocale : DEFAULT_LOCALE;

  return (
    <html lang="en" className="h-full">
      <body className="min-h-full bg-zinc-50 font-sans text-slate-900 antialiased dark:bg-black dark:text-slate-50">
        <Providers initialLocale={initialLocale}>
          <div className="min-h-dvh">
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
